Genres CRUD
yelenskaya/flask-practice pull request #2
Opened 2022-08-04 14:02 UTC by yelenskaya

2022-08-04 15:09 UTC, DenysMoskalenko requested changes

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +        return GenreModel.query.all()
Не делай запросы к бд прям с роутов. Сделай отдельный файл services/crud/dao или че нибудь что больше нравится и реализуй там такие методы, как get_all_genres(), get_genre_by_id(), create_genre() и тд тп. Эти функции у тебя смогут вызываться в разных местах программы, в тестах например. Тебе не нужно будет во многих местах импортировать модель жанров, делать квери, обрабатывать ошибку/ролбек, все что нужно будет сделать - вызвать функцию

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +        genre.name = data.name
Напиши сразу 
genre = GenreModel(name=data.name)

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +        data = genre_request_parser.parse_args()
Никогда не называй переменные data, и вообще если видешь это слово, это должно быть тригером. Очень редки ситуации, когда data уместное слово, в 99% она не нужна. ДЛя примера люди часто пишут genre_data - это абсолютный эквивалент просто написанию genre, ведь мы и так понимаем, что внутри есть какая-то дата. Вообшем для начала просто вот забудь такие слова как data, list, set, ...(другие структуры) в именах переменных.

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +        db.session.commit()
Если например, в моделе поле name будет уникальным, либо станет в будующем таким, то на этом месте у тебя будет ошибка, нужно её отловить и сделать rollback

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/models.py
> +    name = db.Column(db.String(50), nullable=False)
Есть ли смысл иметь 2 жанра с одинаковым именем?
Нужно ли индексировать имя жанра?

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +genres_ns = Namespace(
Если не хочешь писать лишнего, можно назвать просто namespace или ns, и при импорте в инит файле делать
from app.routes.genres import namespace as genres_namespace

Это не ошибка, просто информация)

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +        genre = GenreModel.query.get(id)
Почему тут не использовать то-же что ты использовала в get методе?
Лишний иф уйдет, роут сократится

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +            db.session.commit()
Обработка, ролбек

2022-08-04 15:09 UTC, DenysMoskalenko commented on app/routes/genres.py
> +        genre = GenreModel.query.get(id)
Аналогично методу put

2022-08-05 16:06 UTC, DenysMoskalenko commented on app/services/routes/genres.py
> +        """Delete a genre"""
Вот это те самые бесполезные докстринги, про которые я говорил.
Повторюсь, ничего не имею против, просто наглядный пример

2022-08-05 16:06 UTC, DenysMoskalenko commented on app/services/routes/genres.py
> +            f"Genre with id {id} is deleted",
204 статус код подразумевает, что у тебя не будет тела ответа. Если хочешь писать - шли 200, если хочешь 204 то не шли тело

2022-08-05 16:06 UTC, DenysMoskalenko commented on app/services/routes/genres.py
> +    if not genre:
Если уж у тебя метод называется if_none то лучше будет писать if gente is None

Может прочитать про отличие == и is. genre if None будет работать быстрее.
Если имеешь ввиду, что тебе должен прийти просто falsable обьект genre - тогда переименуй метод

2022-08-07 16:09 UTC, yelenskaya commented on app/services/routes/genres.py
> +ns = Namespace(name="genres", description="Genre operations", path="/genres", validate=True, )
Спасиб, поняла

2022-08-07 16:11 UTC, yelenskaya commented on app/services/dao/genres.py
> +@unique_genre_check
Ну, раз уже начала проверять, то везде ж надо! Случайно, - убрала, спасибо.

2022-08-07 16:12 UTC, yelenskaya commented on app/services/routes/genres.py
> +            f"Genre with id {id} is deleted",
Точняк

2022-08-07 16:14 UTC, yelenskaya commented on app/services/routes/genres.py
> +    if not genre:
Справедливо

2022-08-07 16:20 UTC, yelenskaya commented on app/services/routes/genres.py
> +        """Delete a genre"""
Отсюда они идут в сваггер. Все равно довольно бесполезно, т.к. стандартные методы подразумевают именно ту логику, что и есть, но так немножко красивше?
![image](https://user-images.githubusercontent.com/45938314/183300693-64841f0d-bc41-41fe-bdee-d1493a9ec351.png)

2022-08-07 16:25 UTC, yelenskaya commented on app/services/routes/genres.py
> +        current_app.logger.warn(not_found_message)
Насчет ворнинга сомневалась, так что тут лучше ты скажи как правильно: я сделала ворнинг в тех случаях, когда подразумевается, что жанр должен быть, а его нет - т.е. в случаях update и delete. 

Почему я вообще сделала здесь отдельный лог - наверное, привычка из автотестов, где нужно понимать, какие сущности в системе изменились или не изменились, хотя должны были бы. Наверное, для приложения это и правда покрывается логами фласка.

И еще меня немного запутало условие для проекта - что должны быть логи. Автоматические логи из фласка тогда это условие удовлетворяют?

2022-08-07 16:55 UTC, yelenskaya commented on app/services/dao/genres.py
> +def unique_genre_check(func):
Про wraps почитала, клево!

Про большой кусок кода в try - это ж потому что можно словить не тот эксепшен, который надо? Я думаю, что раз я ловлю максимально специфический эксепшен, это немного компенсируется?

2022-08-08 07:27 UTC, DenysMoskalenko commented on app/services/routes/genres.py
> +        """Delete a genre"""
А, прикольно тогда конечно пусть будут. Restx отсюда берет значит инфу для свагера (Fast-API берет её из названия функции). Но если например это твои личные методы, где докстринги не используются - мысль думаю поняла

2022-08-08 07:29 UTC, DenysMoskalenko commented on app/services/dao/genres.py
> +def unique_genre_check(func):
Я скорее про то, что допустим ты будешь использовать этот декоратор, на какую-то более обьемную функцию, которая будет не только писать в бд, а и выполнять ещё какие-то действия, тогда мы сильно расширим обьем кода в блоке ексепт. В данном случае все норм

2022-08-08 07:35 UTC, DenysMoskalenko commented on app/services/routes/genres.py
> +        current_app.logger.warn(not_found_message)
Как мне кажется, достаточно логов на error если чет пошло не так, + каких-то информативных/варнингов в особо интересные места. Часто логируют что-то с бизнес логикой, те места которые хотелось бы подстветить.

В нашем случае, если хочешь логировать каждую сущность - логируй, я ничего не имею против, но я б этого не делал)
Насчет варнинга, тут мне кажется слишком. Варнин говорит о чем-то на что нужно было б обратить внимание. Но нам не нужно обращать внимание на то, что кто-то попытался создать жанр, который уже есть. Мы не должны обращать внимание на то, что клиент чет делает не так, для отслеживание этого кейса - он получает необходимый респонс.

2022-08-09 19:14 UTC, merged