Directors CRUD with base DAO
yelenskaya/flask-practice pull request #4
Opened 2022-08-11 10:29 UTC by yelenskaya

2022-08-19 08:42 UTC, DenysMoskalenko requested changes

2022-08-19 08:42 UTC, DenysMoskalenko commented on app/__init__.py
>      db_password = os.getenv("POSTGRES_PASS")
Не считывай переменные окружения в этой функции - это все сделай в файле config.py.
Так-же SQLALCHEMY_DATABASE_URI не должна хардкодится, а тоже считываться из .env файла.
Это может быть либо одна такая переменная либо составные чассти: POSTGRESS_USER, POSTGRESS_PASSWORD и тд, которые в коде ты будешь составлять в url

2022-08-19 08:42 UTC, DenysMoskalenko commented on .flake8
> +max-line-length = 120
import-order-style = google  (Нужно установить пакет flake8-import-order)
exclude = migrations, env  (Можно исключить папки, чтоб не сыпались ошибки)
application_import_names = app, tests  (Явно говоришь, какие приложения твои, чтоб при импорте app и tests в одном файле оно оба пакеты считало как твои)

+ не относится к .flake8, но в проекте должен быть файл config.py, wsgi.py и dist.env - По сути аналог твоего локального .env только без сенсетивной даты, чтоб другой разработчик приступая к работе над приложением мог на его основе сделать совй .env файл и знал какие необхзодимые переменные окружения ему нужно определить.

2022-08-19 08:42 UTC, DenysMoskalenko commented on app/daos/base.py
> +            if isinstance(e.orig, StringDataRightTruncation):
Не совсем понятно что тут происходит слишком абстрактное понятие data_error_check - в таких случаях хорошо бы иметь докстригну на функцию(декоратор), которая подробнее бы описывала происходящее

2022-08-19 08:42 UTC, DenysMoskalenko commented on app/utils.py
> +from typing import Optional
Само наличие такого файла не желательно. Чаще всего это говорит о том, что разработчик просто не придумал куда что засунуть.

В нашем случае функция update_model_with_kwargs может находится в файле с BaseDao, хотя самое её наличие мне кажется странным.
С abort_with_404_if_none сложнее, у нас по сути нет пока другого варианта, кроме файла utils/helpers и тд где можно это расположить, но в таком случае этот файл должен находится в папке routes, чтоб относится к нему. В противном случае у нас получается файл на уровне приложения в котором по сути мусорка всего подрят. При росте приложения эта мусорка увеличивается и работать с ней становится тяжело

2022-08-19 08:42 UTC, DenysMoskalenko commented on app/daos/genres.py
> +
Отступ тут не нужен, black по идее поругался бы

2022-08-19 08:42 UTC, DenysMoskalenko commented on app/routes/directors.py
> +    @ns.expect(director_schema)
Тут нужно ожидать director_request_parser. Так-же проверь будет ли оно в таком случае воспринимать пустую строку как валидную

2022-08-19 08:42 UTC, DenysMoskalenko commented on app/routes/directors.py
> +director_request_parser.add_argument("first_name", type=non_empty_str, required=True, help="Director first name")
Нужно указать location=json, по дефолту там по моегму query

2022-08-19 08:42 UTC, DenysMoskalenko commented on pyproject.toml
> +pytest-cov = "^3.0.0"
Уточни плиз для каких целей тебе этот пакет?

2022-08-19 08:42 UTC, DenysMoskalenko commented on tests/test_app_factory.py
> +import os
Не совсем понимаю смысла наличия этого файла, сможешь обьяснить плиз

2022-08-19 08:42 UTC, DenysMoskalenko commented on tests/test_directors.py
> +def create_director_api(client: FlaskClient, first_name: str, last_name: str) -> "TestResponse":
Pycharm не понимает, что за TestResponse
Нужно импортировать from werkzeug.test import TestResponse если хочешь его использовать, так-же по идее нам не нужны кавычки

2022-08-21 17:50 UTC, yelenskaya commented on app/routes/directors.py
> +director_request_parser.add_argument("first_name", type=non_empty_str, required=True, help="Director first name")
Не, там такое: By default, the RequestParser tries to parse values from flask.Request.values, and flask.Request.json.

2022-08-21 17:51 UTC, yelenskaya commented on pyproject.toml
> +pytest-cov = "^3.0.0"
Лишний, из туториала скопировала

2022-08-21 17:57 UTC, yelenskaya commented on app/utils.py
> +from typing import Optional
Попереносила, спасибо. А чего кажется странным update_model_with_kwargs ?

2022-08-21 17:57 UTC, yelenskaya commented on .flake8
> +max-line-length = 120
Суперполезная инфа, спасибо!

2022-08-21 18:19 UTC, yelenskaya commented on app/routes/directors.py
> +director_request_parser.add_argument("first_name", type=non_empty_str, required=True, help="Director first name")
Как оказалось, если передавать в expect парсер а не схему, то и правда надо указывать локейшен, потому что парсит оно нормально, а в сваггер подтягивает как квери

2022-08-21 18:24 UTC, yelenskaya commented on app/routes/directors.py
> +    @ns.expect(director_schema)
Там почему-то можно и так, и так. Если передавать парсер, то чуть другое поведение, напр, оно больше не падает если в строковое поле передается инт или булеан, просто конвертит его в строку. Это ок?
На пустой строке все равно падает.

2022-08-21 18:26 UTC, yelenskaya commented on app/daos/base.py
> +            if isinstance(e.orig, StringDataRightTruncation):
Докстрингу написала, а теперь думаю, наверное длину строки надо проверять еще на этапе реквест парсера?

2022-08-22 09:58 UTC, DenysMoskalenko commented on app/routes/directors.py
> +    @ns.expect(director_schema)
Наверное норм. 
Интересна ситуация, когда будет поле, например номер телефона и ты будешь вводить 380978974582, например, и вот этот номер это же int, но требывать ты его можешь как строку. ЧТо в таком результате будет?

2022-08-22 10:08 UTC, DenysMoskalenko commented on app/utils.py
> +from typing import Optional
Не вижу особого смысла выносить отдельную функцию для этого, оно хорошо себя чувствует и в методе апдейт.
У тебя нет какого-то другого варианта апдейта, только этот. Это почти равносильно том, что в методе create ты б сделала create_model_with_kwargs.

+ не совсем понятно по тайпхинтам. В update у тебя T, а в update_model_with_kwargs уже Model
+ Если б по какой-то причине такой метод был б необходим, он б мог называться просто update_with_kwargs. Это и так находится в дао, где понятно, что мы работаем с моделями. Ты правильно делала, что не усложняла нейминг для основных методов, но для этого чуть усложнила

2022-08-22 10:10 UTC, yelenskaya commented on app/routes/directors.py
> +    @ns.expect(director_schema)
С текущим типом будет эррор. Но я могу добавить другой для телефона

2022-08-22 10:13 UTC, yelenskaya commented on app/utils.py
> +from typing import Optional
Согласна, убрала

2022-08-22 10:14 UTC, DenysMoskalenko commented on app/routes/directors.py
> +    @ns.expect(director_schema)
понял, ну норм пусть так будет

2022-08-22 10:20 UTC, merged