Movies
yelenskaya/flask-practice pull request #5
Opened 2022-08-28 13:58 UTC by yelenskaya

2022-08-29 10:02 UTC, DenysMoskalenko commented on app/daos/base.py
> +            # If column name exists, search by partial text
Каждый такой коментарий - признак плохого кода - избавься от них везде. Если тебе нужна доп информация - пиши в док стринги, если кажется что какая-то часть тяжелая - делай отдельную функцию и тд тп.

2022-08-29 10:08 UTC, DenysMoskalenko commented on app/routes/movies.py
> +query_params_parser.add_argument("query", type=str, location="args", help="Search query")
Не совсем понимаю что за query. Ты предлагаешь фронтенду самому писать запрос на поиск?
Если да, то это очень плохая идея, как минимум фронтенд в основном и не знает толком что такое SQL, а как максимум это возможность SQL иньекции

2022-08-29 10:13 UTC, DenysMoskalenko commented on app/routes/movies.py
> +    # TODO query params query, filter and sort; pagination
Если что-то уже сделанно не забывать убрать TODO

2022-08-29 10:15 UTC, DenysMoskalenko commented on app/daos/movies.py
> +    COLUMN_MAP = {
Нужно ли нам делать этот мэпинг или мы можем обойтись gettatr ?

2022-08-29 10:23 UTC, DenysMoskalenko commented on app/daos/movies.py
> +            query_builder == super()._search(query_builder, search_by_field, query)
== ???

2022-08-29 10:24 UTC, DenysMoskalenko commented on app/routes/movies.py
> +query_params_parser.add_argument("query", type=str, location="args", help="Search query")
Я понял, что это не query, а значение, по которому ищешь. Пожалуйста переименуй

2022-08-29 10:26 UTC, DenysMoskalenko commented on tests/test_genres.py
> +from typing import Optional, Union
Используй Python 3.10, тебе не будут нужны Optional и Union.
Вообще интересно почему ты выбрала 3.9 - если тебя никто не ограничивает - выбирай самую новую версию, на новых все старое прекрасно работает, плюс каждая новая версия мало того, что имеет какие-то приколы, так ещё и тупо быстрее предыдущей.
Прочитай про прирост производительности 3.11, которая выйдет уже совсем скоро

2022-08-29 10:31 UTC, DenysMoskalenko commented on app/daos/base.py
> +    def _filter(self, query_builder: Query, **kwargs) -> Query:
Базовый класс не должен делать подобных вещей.
Если детям будет нужно - они расширят поведение, а думать о всей случаях, которые потребуются детям это путь нетуда

2022-08-29 16:07 UTC, yelenskaya commented on app/daos/movies.py
> +            query_builder == super()._search(query_builder, search_by_field, query)
🤦‍♀️

2022-08-29 23:09 UTC, yelenskaya commented on app/daos/directors.py
> +        super().__init__(model_type=DirectorModel, **kwargs)
column map убрала в пользу getattr(), а инит решила оставить чтоб можно было пользоваться BaseDao в случае нужды

2022-08-29 23:10 UTC, yelenskaya commented on app/daos/base.py
> +    def _filter(self, query_builder: Query, **kwargs) -> Query:
Оставила, т.к. все же нужно, чтоб муви себе сделали кастомный фильтр

2022-08-30 14:35 UTC, DenysMoskalenko requested changes

2022-08-31 06:29 UTC, yelenskaya commented on app/daos/base.py
> +@dataclass
Потому что было мало времени и ты сказал не обращать на это внимание. Почитала базовое про датаклассы, слоты оставила на потом.

2022-08-31 06:36 UTC, yelenskaya commented on app/daos/base.py
> +    order: str
Поменяла на булеан. Изначально сделала asc/desc - потому что это то, как мне попадалось в апишках.

2022-08-31 06:37 UTC, yelenskaya commented on app/routes/movies.py
> +        return movie_dao.get_all(search=search, _filter=_filter, sort=sorting, paginate=paginate)
Спасибо

2022-08-31 06:44 UTC, yelenskaya commented on app/daos/base.py
> +    def _build_pagination(self, query: BaseQuery, paginate: Paginate) -> Pagination:
Хотела доделать до настоящего билдера, в духе query_builder.search(...).filter(...).sort(...).build() и показалось, что проще будет, если оно уже поделенное по методам будет. 
Плюс ты говорил про полотно и что надо убрать комменты. В общем, не так поняла, значит.

2022-08-31 07:19 UTC, yelenskaya commented on app/daos/movies.py
> +            query = self._build_genres_search_query(partial_text_query)
Поменяла северити для этого. Иногда пропускаю ворнинги среди ворнингов про декларативную алхимию. Ну и тесты надо доделать.

2022-08-31 07:45 UTC, yelenskaya commented on app/daos/base.py
> +            return self._build_pagination(query, paginate).items
Аттрибут эррор

2022-08-31 08:10 UTC, DenysMoskalenko commented on app/daos/base.py
> +@dataclass
https://www.youtube.com/watch?v=Fot3_9eDmOs

2022-08-31 08:11 UTC, DenysMoskalenko approved these changes

2022-08-31 10:16 UTC, merged